services:
  ollama:
    image: ollama/ollama
    container_name: ollama
    attach: false
    ports:
      - "11434:11434"
    volumes:
      - ollama:/root/.ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    restart: unless-stopped

  mininet:
    build:
      context: .
    image: mininet
    tty: true
    stdin_open: true
    privileged: true
    environment:
     - DISPLAY
    volumes:
     - /tmp/.X11-unix:/tmp/.X11-unix
     - /lib/modules:/lib/modules

volumes:
  ollama:
